server:
    port: ${port:9080}
   
    context-path: /
    error.whitelabel.enabled: false
    session.timeout: 60
    compression:
      enabled: true
      min-response-size: 1024
      mime-types: text/html, text/xml, text/plain, text/css, application/javascript, application/json
tomcat:
    ajp.port: 10080
    ajp.remoteauthentication: false
    ajp.enabled: true
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: australian           
      clientSecret: 12d0d3b6fc21577312aa3598b597ea921dc79b8c8c78dd0a2d2045ab326d6525f6ffad1a2275032a7227e171322511b1   
      accessTokenUri: https://australian.plateau.com/learning/oauth-api/rest/v1/token   
      userAuthorizationUri: http://localhost:8280/auth/realms/demo-realm/protocol/openid-connect/auth
    resource:
      userInfoUri: http://localhost:8280/auth/realms/demo-realm/protocol/openid-connect/userinfo
      
# LOGGING
logging.level.org.springframework.security: DEBUG
logging.level.com.unityhealth.api.retrieveUserInfo: DEBUG

logging:
  level:
    
    org.springframework.web: DEBUG
    root: WARN
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /ithera-application-new.log

spring:
  profiles: default
  mail:

      host: mail.iinet.net.au
      username: info@imgateway.net
      password:
      port: 25
      properties.mail.smtp.auth: false
      email-contactus-to-address: office@unityhealth.com.au,office@unityhealth.com.au
      email-contactus-from-address: info@imgateway.net
      email-contactus-subject: SELF - Contact Us
  jackson:
  serialization:
  fail-on-empty-beans: false


  
selfDbClient:
  hibernate:
    hbm2ddl.auto: none
    dialect: org.hibernate.dialect.MySQLDialect
  jdbc:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/itherapeutics_au_rx
    username: root
    password: qwasz2004!
  pool:
    maxPoolSize: 10
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
            
breezeDbClient:
  hibernate:
    hbm2ddl.auto: none
    dialect: org.hibernate.dialect.SQLServerDialect
  jdbc:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:sqlserver://183.177.57.90:1433;databaseName=breeze;
    username: sa
    password: qwasz2004!
  pool:
    maxPoolSize: 10
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none

itheraImagePath: file:E:\\work\\www.itherapeutics.com.au\\web\\
commonImagePath: file:E:\\work\\www.itherapeutics.com.au\\web\\
amcalImagePath: file:E:\\work\\www.itherapeutics.com.au\\web\\
guardianImagePath: file:E:\\work\\www.itherapeutics.com.au\\web\\

adobeConnect: https://connect.itherapeutics.com.au
adobeConnectAdmin: info@itherapeutics.com.au
adobeConnectAdminPassword: qwasz2004!
adobeConnectApi: https://connect.itherapeutics.com.au/api/xml
breezeLearnersGroupSCO: 88900

jsonFilePath: E:\\retrieveUserInfo\\

session:
 store-type: none

rewardprogram:
 enabled: true
 name:
  enabled: true
  label: iRewards

 status1:
  perc: 80
  name:
   enabled: true
   label: Gold
 status2:
  perc: 0
  name:
   enabled: true
   label: Silver
 status3:
  perc: 0
  name:
   enabled: true
   label: Bronze
 startdate: 2013-04-01
 redeem:
  shop:
   delivery:
    weeks: 
     text: 6-8
 
baseSystem: SELF


secured.service.url : http://localhost:8080/message
 
logging.level.org.springframework.web: debug
logging.level.org.keycloak : debug

logging.level.org.springframework.web-security: trace
 

  