server:
    port: ${port:9080}
    context-path: /
    error.whitelabel.enabled: false
    session.timeout: 60
    compression:
      enabled: true
      min-response-size: 1024
      mime-types: text/html, text/xml, text/plain, text/css, application/javascript, application/json

security:
  basic:
    enabled: false
  oauth2:
    sso:
      loginPath: /login
    resource:
      jwt:
        keyValue: |
              -----BEGIN PUBLIC KEY-----
              MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
              -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource
      
# LOGGING
# logging.level.org.springframework.security: DEBUG

logging:
  level:
    org.springframework.web: INFO
    root: WARN
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /ithera-application-new.log

spring:
  profiles: default
  mail:

      host: mail.iinet.net.au
      username: info@imgateway.net
      password:
      port: 25
      properties.mail.smtp.auth: false
      email-contactus-to-address: office@unityhealth.com.au,office@unityhealth.com.au
      email-contactus-from-address: info@imgateway.net
      email-contactus-subject: SELF - Contact Us
  jackson:
  serialization:
  fail-on-empty-beans: false


  
selfDbClient:
  hibernate:
    hbm2ddl.auto: none
    dialect: org.hibernate.dialect.MySQLDialect
  jdbc:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/itherapeutics_au_rx
    username: root
    password: qwasz2004!
  pool:
    maxPoolSize: 10
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none

itheraImagePath: file:E:\\work\\www.itherapeutics.com.au\\web\\
commonImagePath: file:E:\\work\\www.itherapeutics.com.au\\web\\
amcalImagePath: file:E:\\work\\www.itherapeutics.com.au\\web\\
guardianImagePath: file:E:\\work\\www.itherapeutics.com.au\\web\\

adobeConnect: https://connect.itherapeutics.com.au
adobeConnectAdmin: info@itherapeutics.com.au
adobeConnectAdminPassword: qwasz2004!
adobeConnectApi: https://connect.itherapeutics.com.au/api/xml
breezeLearnersGroupSCO: 88900

session:
 store-type: none

rewardprogram:
 enabled: true
 name:
  enabled: true
  label: iRewards

 status1:
  perc: 80
  name:
   enabled: true
   label: Gold
 status2:
  perc: 0
  name:
   enabled: true
   label: Silver
 status3:
  perc: 0
  name:
   enabled: true
   label: Bronze
 startdate: 2013-04-01
 redeem:
  shop:
   delivery:
    weeks: 
     text: 6-8
 
baseSystem: SELF
